### ISSUE TITLE
下载后 在mac端下 使用 idea 运行不了 

### ISSUE THREAD

**Issue by yuhe520521** [code4everything/efo#1]
显示缺少很多的包 我确认 pom 文件里的包 都已经自动下载完成了
基本上就是以下这样的报错  
Error:(5, 26) java: 程序包com.zhazhapan.util不存在
Error:(7, 30) java: 程序包org.apache.ibatis.jdbc不存在

请问我哪里弄的不对么？

**Comment by zhazhapan** [comment]
你clean一下maven项目，重新install试试呢
